---
name: adguard-home

services:
  adguard-home:
    image: adguard/adguardhome:v0.107.74
    container_name: adguard-home
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - NET_BIND_SERVICE
      - SETUID
      - SETGID
    mem_limit: 256m
    network_mode: host
    volumes:
      - ./work:/opt/adguardhome/work
      - ./conf:/opt/adguardhome/conf
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
