---
name: CI

on:
  push:
    branches: [main]
    paths:
      - '*/docker-compose.yml'
      - '*/.env.example'
      - 'scripts/*.sh'
      - 'stacks'
      - '.github/workflows/ci.yml'
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Run lint
        run: ./scripts/lint.sh
